[package]
name = "portfolio"
description = "My personal website. Very basic."
edition = "2021"
repository = "https://git.average.name/AverageHelper/portfolio"
authors = ["AverageHelper"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = { version = "1.3.1", default-features = false }
include_dir = "0.7.4"
rand = "0.8.5"
rocket = "0.5.1"
rocket_async_compression = "0.6.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
url = "2.5.4"

[lints.rust]
unsafe_code = "forbid"

[[bin]]
name = "portfolio"
path = "functions/main.rs"
