# Audits us against the RustSec database

name: Security audit

on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  schedule:
    # Every week
    - cron: "0 7 * * 0"
  workflow_dispatch:

jobs:
  security-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install rustup
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Setup Rust toolchain
        run: |
          . "$HOME/.cargo/env"
          rustup update stable && rustup default stable
          cargo install cargo-audit --locked

      - name: RustSec audit check
        run: |
          . "$HOME/.cargo/env"
          cargo audit
