on:
  push:
    branches: [main]
    paths:
      - .forgejo/workflows/**
      - functions/**
      - public/**
      - src/**
      - astro.config.ts
      - deno.jsonc
      - deno.lock
      - package-lock.json
      - package.json
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup deno
        uses: https://github.com/denoland/setup-deno@v1
        with:
          deno-version: v2.0.3

      - name: Install Dependencies
        run: |
          deno install --frozen
          npm ci

      - name: Build
        run: deno task build

      - name: Test
        run: deno task test
