on:
  push:
    branches: [main]
    paths:
      - .forgejo/workflows/**
      - functions/**
      - public/**
      - src/**
      - astro.config.ts
      - deno.jsonc
      - deno.lock
      - package-lock.json
      - package.json
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup deno
        uses: https://github.com/denoland/setup-deno@v1
        with:
          deno-version: v2.0.3

      - name: Install rustup
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Setup Rust toolchain
        run: |
          . "$HOME/.cargo/env"
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Install Dependencies
        run: |
          deno install --frozen
          npm ci

      - name: Build
        run: deno task build

      - name: Test
        run: |
          . "$HOME/.cargo/env"
          cargo test --verbose --locked
